export const WS_CONNECTION_START: "WS_CONNECTION_START" = "WS_CONNECTION_START";
export const WS_CONNECTION_SUCCESS: "WS_CONNECTION_SUCCESS" =  "WS_CONNECTION_SUCCESS";
export const WS_CONNECTION_ERROR: "WS_CONNECTION_ERROR" = "WS_CONNECTION_ERROR";
export const WS_CONNECTION_CLOSE: "WS_CONNECTION_CLOSE" = "WS_CONNECTION_CLOSE";
export const WS_CONNECTION_CLOSED: "WS_CONNECTION_CLOSED" = "WS_CONNECTION_CLOSED";
export const WS_GET_MESSAGE: "WS_GET_MESSAGE" = "WS_GET_MESSAGE";

export const USER_REGISTER_FORM_SET_VALUE: "USER_REGISTER_FORM_SET_VALUE" = "USER_REGISTER_FORM_SET_VALUE";
export const USER_REGISTER_FORM_SUBMIT: "USER_REGISTER_FORM_SUBMIT" = "USER_REGISTER_FORM_SUBMIT";
export const USER_REGISTER_FORM_SUBMIT_SUCCESS: "USER_REGISTER_FORM_SUBMIT_SUCCESS" = "USER_REGISTER_FORM_SUBMIT_SUCCESS";
export const USER_REGISTER_FORM_SUBMIT_FAILED: "USER_REGISTER_FORM_SUBMIT_FAILED" = "USER_REGISTER_FORM_SUBMIT_FAILED";

export const USER_LOGIN_FORM_SET_VALUE: "USER_LOGIN_FORM_SET_VALUE" = "USER_LOGIN_FORM_SET_VALUE";
export const USER_LOGIN_FORM_SUBMIT: "USER_LOGIN_FORM_SUBMIT" = "USER_LOGIN_FORM_SUBMIT";
export const USER_LOGIN_FORM_SUBMIT_SUCCESS: "USER_LOGIN_FORM_SUBMIT_SUCCESS" =  "USER_LOGIN_FORM_SUBMIT_SUCCESS";
export const USER_LOGIN_FORM_SUBMIT_FAILED: "USER_LOGIN_FORM_SUBMIT_FAILED" = "USER_LOGIN_FORM_SUBMIT_FAILED";

export const USER_ACCESS_ALLOWED: "USER_ACCESS_ALLOWED" = "USER_ACCESS_ALLOWED";
export const USER_ACCESS_DENIED: "USER_ACCESS_DENIED" = "USER_ACCESS_DENIED";

export const FORGOT_PASSWORD_FORM_SET_VALUE: "FORGOT_PASSWORD_FORM_SET_VALUE" = "FORGOT_PASSWORD_FORM_SET_VALUE";
export const FORGOT_PASSWORD_FORM_SUBMIT: "FORGOT_PASSWORD_FORM_SUBMIT" = "FORGOT_PASSWORD_FORM_SUBMIT";
export const FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS: "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS" = "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS";
export const FORGOT_PASSWORD_FORM_SUBMIT_FAILED: "FORGOT_PASSWORD_FORM_SUBMIT_FAILED" = "FORGOT_PASSWORD_FORM_SUBMIT_FAILED";

export const RESET_PASSWORD_FORM_SET_VALUE: "RESET_PASSWORD_FORM_SET_VALUE" = "RESET_PASSWORD_FORM_SET_VALUE";
export const RESET_PASSWORD_FORM_SUBMIT: "RESET_PASSWORD_FORM_SUBMIT" = "RESET_PASSWORD_FORM_SUBMIT";
export const RESET_PASSWORD_FORM_SUBMIT_SUCCESS: "RESET_PASSWORD_FORM_SUBMIT_SUCCESS" = "RESET_PASSWORD_FORM_SUBMIT_SUCCESS";
export const RESET_PASSWORD_FORM_SUBMIT_FAILED: "RESET_PASSWORD_FORM_SUBMIT_FAILED" = "RESET_PASSWORD_FORM_SUBMIT_FAILED";

export const CHANGE_USER_DATA_FORM_SUBMIT: "CHANGE_USER_DATA_FORM_SUBMIT" =  "CHANGE_USER_DATA_FORM_SUBMIT";
export const CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS: "CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS" = "CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS";
export const CHANGE_USER_DATA_FORM_SUBMIT_FAILED: "CHANGE_USER_DATA_FORM_SUBMIT_FAILED" =  "CHANGE_USER_DATA_FORM_SUBMIT_FAILED";

export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const SORT_INGREDIENTS: "SORT_INGREDIENTS" = "SORT_INGREDIENTS";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const RESET_INGREDIENT: "RESET_INGREDIENT" = "RESET_INGREDIENT";

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" = "GET_INGREDIENTS_FAILED";

export const SET_CURRENT_INGREDIENT: "SET_CURRENT_INGREDIENT" = "SET_CURRENT_INGREDIENT";
export const RESET_CURRENT_INGREDIENT: "RESET_CURRENT_INGREDIENT" = "RESET_CURRENT_INGREDIENT";

export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const RESET_ORDER: "RESET_ORDER" = "RESET_ORDER";